### ISSUE TITLE
fakecall

### ISSUE THREAD

**Issue by sk3lk0** [R1iaz/fakecall#2]
dont working

**Comment by razisek** [comment]
Really?

**Comment by sk3lk0** [comment]
Method is not allowed

сб, 31 марта 2018 г., 9:30 Azis <notifications@github.com>:

**Comment by sk3lk0** [comment]
its not working only for me or they make protect?

**Comment by razisek** [comment]
no, it still works

**Comment by FelixDeluxStar** [comment]
it doesn't work for me. How do I enter a number with + or not? Country code to enter? Forward to hearing.
